version: 2.1
jobs:
  message:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "builidng pipeline...."
workflows:
  message-workflow:
    jobs:
      - message
