appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.4.1
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "1"
- name: ENV_VAR_TWO
  value: "2"


serviceType: ClusterIP
servicePort: 8080