appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo/checkoutservice
appVersion: v0.4.1
appReplicas: 2
containerPort: 5050
containerEnvVars:
- name: PORT
  value: "5050"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:8080"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"

serviceType: ClusterIP
servicePort: 5050