appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.4.1
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"


serviceType: ClusterIP
servicePort: 5000