appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.4.1
appReplicas: 2
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"

serviceType: ClusterIP
servicePort: 3550